### ISSUE TITLE
Adicionar declaração de todas as dependências para um deploy 

### ISSUE THREAD

**Issue by yamadapc** [haskellbr/website#1]
Deve haver uma forma declarativa de reproduzir:
- [ ] A configuração do proxy reverso `nginx` no momento
- [ ] O serviço `slackin`
- [ ] O serviço `slack-irc`
- [ ] O serviço `haskellbr-website`
- [ ] Outros potenciais serviços

Talvez nem todos esses caibam nesse repositório.

**Comment by asakeron** [comment]
O [nixops](https://github.com/NixOS/nixops) possibilita a especificação da configuração de máquinas declarativamente e é uma ferramenta para deploy. Ainda não tive a chance de usar, mas estou disposto a estudá-la se for o caso.

**Comment by yamadapc** [comment]
Acho meio complicado; não queria ir tão longe.

**Comment by yamadapc** [comment]
Vou fechar essa issue já que solucionei ela em um projeto fechado.
